---
title: 'Reproducible Research: Peer Assessment 1'
output:
  html_document:
    keep_md: yes
  pdf_document: default
  word_document: default
---

## Libraries 
```{r}
library("dplyr")
```




## Loading and preprocessing the data
### Unzip Data File
```{r}
if(!file.exists("activity.csv"))
{
  unzip("activity.zip")
}
```
### Load data
```{r}
dataActivity <- read.csv("activity.csv")
```


### Some summary statistics
```{r}
summary(dataActivity)
```

How many days exists in data set?

```{r}
unique(dataActivity$date)
```




## What is mean total number of steps taken per day?


```{r}
dataActivityNARemoved <- dataActivity[complete.cases(dataActivity),]

totalsGroupedByDate <- dataActivityNARemoved %>%
  group_by(date) %>%
  select(steps, date) %>%
  summarise(
    sumStep = sum(steps, na.rm = TRUE)
  ) 
breakSize <-dim(totalsGroupedByDate)[1]
hist(totalsGroupedByDate$sumStep,breaks=breakSize,main="Total Steps taken each day",ylab="totalSteps",xlab="date")
```

### mean 
```{r}
mean(totalsGroupedByDate$sumStep)
```

### median 

```{r}
median(totalsGroupedByDate$sumStep)
```



## What is the average daily activity pattern?
```{r}
averageGroupedByInterval <- dataActivity %>%
  group_by(interval) %>%
  select(steps, interval) %>%
  summarise(
    averageStep = mean(steps, na.rm = TRUE)
  ) 

plot(averageGroupedByInterval$interval,averageGroupedByInterval$averageStep,type="l",xlab="intervals",ylab="average steps for every day",main="average number of steps taken each 5 minute interval")

```
  

## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
